### ISSUE TITLE
Añadir .gitignore

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#1]
Deberías añadir un fichero .gitignore a la raíz del repositorio para que omita las carpetas node_modules, dependiendo de las dependencias que sean a veces no solo contienen JS/TS sino también código que se compila en cada arquitectura y es un dolor de cabeza si no te das cuenta de que puede ser el origen de los problemas.

Un ejemplo extenso: https://www.gitignore.io/api/node
O usando NPM: https://github.com/msfeldstein/gitignore

Además así serán más rápidos los commits al no subir tantos directorios de módulos

**Comment by manumedinat** [comment]
He insertado el fichero gitignore para omitar 'node_modules'.

Espero que funcione bien y gracias por el apunte!
