### ISSUE TITLE
Review the pom.xml generation #enhancement

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#10]
Rewrite the pom.xml file generation, based on this https://github.com/manumedinat/TFG/issues/6

**Comment by daniel-dona** [comment]
Ref: https://github.com/manumedinat/TFG/blob/b66f1ea3cd122cb44e6173dbce1eb3db30979c64/R2RML/ServerGenerator.js#L50

**Comment by manumedinat** [comment]
With the new updates done both for index.js and serverGenerator.js, the creation of the pom.xml consists on overwriting the pom completely with the dependencies needed.
