### ISSUE TITLE
Código generado

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#4]
He intentado generar el código en Java, pero lo único que me genera es una estructura de directorios en prueba2

```
.
└── src
    └── main
        ├── java
        │   └── com
        │       └── example
        │           └── demo
        │               ├── mutation
        │               └── query
        └── resources
            └── graphql

10 directories, 0 files
```

Quizá hay algo que no estoy haciendo bien, he seguido tal cual los pasos del readme un par de veces. En "prueba" me quedo con la plantilla de Spring pero no parece que luego se modifique ni le añada nada.

No sé si hay algo que se me escapa...

**Comment by manumedinat** [comment]
Buenas,

He quitado los comentarios de las líneas correspondientes para que así se genere el texto perteneciente a cada fichero. 

Dime a ver si te funciona ya cuando puedas
