### ISSUE TITLE
Remove the yeoman dependency #enhancement

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#6]
As yeoman is only a template generator, the generated template can be used as an input for morph-graphql, no need to execute yeoman every time as the result is expected to be always the same.

Also, the generated template file and folder structure should be documented somewhere. A simple `tree` command will do the trick...

**Comment by manumedinat** [comment]
Yeoman dependency has been removed using a template zip and a npm library called 'unzip' to generate the server
