### ISSUE TITLE
Write a deployment batch script #enhancement

### ISSUE THREAD

**Issue by daniel-dona** [manumedinat/TFG#7]
Would be great to have some `run.sh` script to launch the generator and the generated resolvers, to simplify future code launch and testing.

**Comment by daniel-dona** [comment]
Precondition: https://github.com/manumedinat/TFG/issues/6

**Comment by daniel-dona** [comment]
Precondition: https://github.com/manumedinat/TFG/issues/8

**Comment by manumedinat** [comment]
startup.bat has been created to simplify this process, but I am not able to remove spring-initializr and yeoman so as to create the template project. Could you tell me some tips?

**Comment by manumedinat** [comment]
startup.bat now includes all the steps needed to generate the server automatically.
